# Generated by Django 3.2.25 on 2025-11-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20251120_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='user_type',
            field=models.CharField(default='user', editable=False, max_length=100),
        ),
    ]
