# Generated by Django 3.2.25 on 2025-12-06 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='multivendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('restaurant_lic', models.ImageField(blank=True, null=True, upload_to='licience_pics/')),
                ('restaurant_img', models.ImageField(blank=True, null=True, upload_to='restaurent_pics/')),
                ('user_type', models.CharField(default='vendor', editable=False, max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='menubuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('food_img', models.ImageField(blank=True, null=True, upload_to='food_img/')),
                ('ver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multivendorss', to='vendors.multivendors')),
            ],
        ),
    ]
