# Generated by Django 5.2.7 on 2025-12-13 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='multivendors',
            name='Franchise',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_investment', models.DecimalField(decimal_places=2, help_text='Total investment required in currency', max_digits=10)),
                ('total_year_of_agreement', models.PositiveIntegerField(help_text='Duration of agreement in years')),
                ('profit_share', models.DecimalField(decimal_places=2, help_text='Profit share percentage (0-100)', max_digits=5)),
                ('description', models.TextField(blank=True, default='Join our growing franchise network and be part of a successful food delivery ecosystem. We provide comprehensive training, marketing support, and operational guidance to ensure your success. Our franchisees enjoy steady revenue streams and proven business models.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='franchise_vendors', to='vendors.multivendors')),
            ],
        ),
    ]
