# Generated by Django 5.2.7 on 2025-12-13 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_multivendors_franchise_franchise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franchise',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='franchise',
            name='total_year_of_agreement',
        ),
        migrations.RemoveField(
            model_name='franchise',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='franchise',
            name='user',
        ),
        migrations.AddField(
            model_name='franchise',
            name='total_year_of_aggr',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='franchise',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='profit_share',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='total_investment',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='franchises', to='vendors.multivendors'),
        ),
    ]
